### ISSUE TITLE
Efficiency Calculator - Relics to spend

### ISSUE THREAD

**Issue by Nullception** [colblitz/YATTO#1]
When using the "Relics to spend" field the artifact summary is always over the amount of relics you initially set. Ex: If you put in 40000 and start to level up the artifacts based on the summary you will end up with at least one or two artifacts above the total relics you can spend.

I have tested this on both R/s and TDmg.

**Comment by Nullception** [comment]
I am assuming you have recently resolved this issue because I was able to complete the summary without issue twice now.

**Comment by colblitz** [comment]
...huh. The fix is pushed, but I'm pretty sure I never deployed it. Have you tried it with the same values where you couldn't finish all the steps?

**Comment by Nullception** [comment]
Odd, well I will have to try it again when I prestige again. I tried it last with 52k and it seemed to work but that might have just been a total that didnt cause the bug to show up. I will let you know. Thanks again for the awesome app!
