### ISSUE TITLE
How to Run YATTO Locally

### ISSUE THREAD

**Issue by soupskidz** [colblitz/YATTO#21]
I am not a technical person, but since the YATTO website has long since shut down, is there any way for me to run this locally on my computer? Thanks

**Comment by colblitz** [comment]
Hey, so I started it up again if you're ok with it being a few versions out of date (I think I last updated it for 4.1.1, and it looks like TT is now on 4.1.6?).

Besides that, you definitely can run it locally, though it does take a bit of effort. If you have some familiarity with a terminal, the broad strokes would be

- Download the code (`git clone https://github.com/colblitz/YATTO.git`)
- Install dependencies (`npm install` from within the YATTO directory)
- Install and run mongodb
- Run the YATTO webserver locally (`npm start` from within the YATTO directory)
- Go to `localhost:3000` in a browser

However, I just tried that and got some version incompatibility issues (it's using an old version of MongoDB that I can't even find an install link for), and a fix for that might be easy or hard but would take time to figure out.
